<?php

/* Copyright(c) Curtis Zimmerman and L0j1k.com                        */
/* This is all subject to the Creative Commons License, found at:     */
/* http://creativecommons.org/licenses/by-nc-sa/2.0/                  */
/*                                                                    */
/* You can find the original tinyMuw script at:                       */
/* http://www.L0j1k.com/tinyMuw/index.php                             */

include 'tinyMuw/config.php';
include 'tinyMuw/database.php';
?>