<?php
include('config.php');
include('database.php');
/* Mail.php -- encapsulates all the mailing, so that no other object has access to the */
/* mail() function, thereby increasing security. */
class mailer {
   var $ipAddr;  /* We want to store the IP address of the offender no matter what! */

   function mailer() {
      $this->ipAddr = $session->ipAddr;
   }

   function mailAdmin($internal, $errorBad, $ip, $priority) {
      global $session;
      if($internal == internalCall) {
	     $subject = 'URGENT! '.siteName.' hack attempt!';
		 $message = '<body><h2><div align="center">'.siteName.' Hack Attempt!</div></h2>';
		 $message .= '<p>There has been a serious error on your site that triggered tinyMuw to ';
	     $message .= 'email you to take immediate action.<br><br>The following error(s) was ';
		 $message .= 'generated on ';
		 $message .= date('D dMY \a\t H:i:s e',$session->timeNow);
		 $message .= '<br><br>'.$errorBad.'<br>Logged IP: '.$ip.'<br>Priority: '.$priority.'<br><br>';
		 $message .= 'Obviously, you need to login and take care of this, or ban the IP, or something.';
		 $message .= '<br><br>';
		 $message .= 'The good thing is that if you happen to be on the beach right now and this happens ';
		 $message .= 'more than a few times, I will go ahead and ban the IP automagically.</p></body>';		    
	     $headers .= "From: ".adminEmail."\r\n";
		 $headers .= "Reply-To: ".adminEmail."\r\n";
   		 $headers .= "X-Mailer: PHP/".phpversion()."\r\n";
		 $headers .= "Content-Type: text/html\r\n";
		 $email = adminEmail;
	     if(mail($email, $subject, $message, $headers)) {
		    return true;
		 } else {
		    return false;
		 }
	  } else {  /* LOL. Someone tried to hack the emergency mailAdmin() function. */
	     $errorBad = "mailer.mailAdmin() internalCall incorrect. IMPORTANT because of mail() function!";
		 $priority = '1';
		 $session->errorBad($errorBad, $priority);
	  }
   }
   
   function mailConfirm($internal, $username, $email, $itempPassword) {
      global $session;
      if($internal == internalCall) {
	     /* We should actually consider loading this from a flatfile, so that */
		 /* people who download it can change the content of their registration */
		 /* emails as they please. */
		 $subject = siteName.' Account Registration';
		 $message = '<body><h2><div align="center">'.siteName.' Account Registration</div></h2>';
		 $message .= '<p>Hello and thank you for registering at '.siteName.'!<br><br>';
		 $message .= 'In order to activate your account (verifying this email address), ';
		 $message .= 'you need to log in <a href="'.webRoot.indexPage.'">here</a> ';
		 $message .= 'using the following randomly-generated ';
		 $message .= 'password: '.$itempPassword.'  <br><br>';
		 $message .= 'The password you registered with will become your new login ';
		 $message .= 'password as soon as you have logged in with this temporary one. ';
		 $message .= 'If you have any questions or concerns, or wish to un-register your ';
		 $message .= 'account for any reason, please email the administrator at '.adminEmail.'.<br><br>';
		 $message .= 'Thanks!<br><br>-Admin<br><br>';
		 $message .= 'This Email was generated by the tinyMuw Content Management System.<br><br>';
		 $message .= 'Learn more and download it free at <a href="http://www.tinyMuw.com">tinyMuw.com</a>!</p>';
		 $message .= '</body>';
		 $headers .= "From: ".adminEmail."\r\n";
		 $headers .= "Reply-To: ".adminEmail."\r\n";
   		 $headers .= "X-Mailer: PHP/".phpversion()."\r\n";
		 $headers .= "Content-Type: text/html\r\n";
	     if(mail($email, $subject, $message, $headers)) {
		    return true;
		 } else {
		    return false;
		 }
	  } else {  /* Hack attempt on a not-so-good function to get hack-attempted. */
		 $error = "mailer.mailConfirm() internalCall incorrect. IMPORTANT because of mail() function!";
		 $priority = '1';
		 $session->errorBad($errorBad, $priority);
	  }
   }
   
   function forgotPass($internal, $email, $username, $ipasswordHashed) {
      global $session;
      if($internal == internalCall) {
	     /* We should actually consider loading this from a flatfile, so that */
		 /* people who download it can change the content of their registration */
		 /* emails as they please. */
		 $subject = siteName.' Forgotten Account Information';
		 $message = '<body><h2><div align="center">'.siteName.' Account Information</div></h2>';
		 $message .= '<p>You are receiving this email because you, or someone who knows your ';
		 $message .= 'email address has requested new account information at '.siteName.'!<br><br>';
		 $message .= 'In order to restore your account (verifying this email address), ';
		 $message .= 'you need to log in <a href="'.webRoot.indexPage.'">here</a> ';
		 $message .= 'using the following login information:<br><br> ';
		 $message .= 'Username: '.$username.'<br><br>';
		 $message .= 'Temporary Password: '.$ipasswordHashed.'<br><br>';
		 $message .= 'You will be required to change your password as soon as you log in. ';
		 $message .= '<br><br>';
		 $message .= 'If you have any questions or concerns, or wish to un-register your ';
		 $message .= 'account for any reason, please email the administrator at '.adminEmail.'.<br><br>';
		 $message .= 'Thanks!<br><br>-Admin<br><br>';
		 $message .= 'This Email was generated by the tinyMuw Content Management System.<br><br>';
		 $message .= 'Learn more and download it free at <a href="http://www.tinyMuw.com">tinyMuw.com</a>!</p>';
		 $message .= '</body>';
		 $headers .= "From: ".adminEmail."\r\n";
		 $headers .= "Reply-To: ".adminEmail."\r\n";
   		 $headers .= "X-Mailer: PHP/".phpversion()."\r\n";
		 $headers .= "Content-Type: text/html\r\n";
	     if(mail($email, $subject, $message, $headers)) {
		    return true;
		 } else {
		    return false;
		 }
	  } else {  /* Else eine Hacker. Not Else the Hacker. I guess I should say oder ein Hacker. */
	     $error = "mailer.forgotPass() internalCall incorrect. IMPORTANT because of mail() function!";
		 $priority = '1';
		 $session->errorBad($errorBad, $priority);
	  }
   }
   
   function mailNewUser($internal, $usernameWanted, $email, $password) {
   global $session;
      if($internal == internalCall) {
	     /* We should actually consider loading this from a flatfile, so that */
		 /* people who download it can change the content of their registration */
		 /* emails as they please. */
		 $subject = siteName.' New Account Information';
		 $message = '<body><h2><div align="center">'.siteName.' Account Information</div></h2>';
		 $message .= '<p>You are receiving this email because the administrator of this website ';
		 $message .= 'has requested a new account for you at '.siteName.'!<br><br>';
		 $message .= 'Please log in <a href="'.webRoot.indexPage.'">here</a> ';
		 $message .= 'using the following login information:<br><br> ';
		 $message .= 'Username: '.$username.'<br><br>';
		 $message .= "Password: ".$password."<br /><br />";
		 $message .= 'If you have any questions or concerns, or wish to un-register your ';
		 $message .= 'account for any reason, please email the administrator at '.adminEmail.'.<br><br>';
		 $message .= 'Thanks!<br><br>-Admin<br><br>';
		 $message .= 'This Email was generated by the tinyMuw Content Management System.<br><br>';
		 $message .= 'Learn more and download it free at <a href="http://www.tinyMuw.com">tinyMuw.com</a>!</p>';
		 $message .= '</body>';
		 $headers .= "From: ".adminEmail."\r\n";
		 $headers .= "Reply-To: ".adminEmail."\r\n";
   		 $headers .= "X-Mailer: PHP/".phpversion()."\r\n";
		 $headers .= "Content-Type: text/html\r\n";
	     if(mail($email, $subject, $message, $headers)) {
		    return true;
		 } else {
		    return false;
		 }
	  } else {  /* Else eine Hacker. Not Else the Hacker. I guess I should say oder ein Hacker. */
	     $error = "mailer.mailNewUser() internalCall incorrect. IMPORTANT because of mail() function!";
		 $priority = '1';
		 $session->errorBad($errorBad, $priority);
	  }
   }
}
$mailer = new mailer;
?>